// Code generated by MockGen. DO NOT EDIT.
// Source: mishin-gophermat/internal/handlers/postorders (interfaces: OrderCreator)

// Package postorders is a generated GoMock package.
package postorders

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOrderCreator is a mock of OrderCreator interface.
type MockOrderCreator struct {
	ctrl     *gomock.Controller
	recorder *MockOrderCreatorMockRecorder
}

// MockOrderCreatorMockRecorder is the mock recorder for MockOrderCreator.
type MockOrderCreatorMockRecorder struct {
	mock *MockOrderCreator
}

// NewMockOrderCreator creates a new mock instance.
func NewMockOrderCreator(ctrl *gomock.Controller) *MockOrderCreator {
	mock := &MockOrderCreator{ctrl: ctrl}
	mock.recorder = &MockOrderCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderCreator) EXPECT() *MockOrderCreatorMockRecorder {
	return m.recorder
}

// OrderByNumberGet mocks base method.
func (m *MockOrderCreator) OrderByNumberGet(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderByNumberGet", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderByNumberGet indicates an expected call of OrderByNumberGet.
func (mr *MockOrderCreatorMockRecorder) OrderByNumberGet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderByNumberGet", reflect.TypeOf((*MockOrderCreator)(nil).OrderByNumberGet), arg0, arg1)
}

// OrderCreate mocks base method.
func (m *MockOrderCreator) OrderCreate(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderCreate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// OrderCreate indicates an expected call of OrderCreate.
func (mr *MockOrderCreatorMockRecorder) OrderCreate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderCreate", reflect.TypeOf((*MockOrderCreator)(nil).OrderCreate), arg0, arg1, arg2)
}
