// Code generated by MockGen. DO NOT EDIT.
// Source: mishin-gophermat/internal/handlers/postorders (interfaces: AbstrStorage)

// Package orders is a generated GoMock package.
package postorders

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAbstrStorage is a mock of AbstrStorage interface.
type MockAbstrStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAbstrStorageMockRecorder
}

// MockAbstrStorageMockRecorder is the mock recorder for MockAbstrStorage.
type MockAbstrStorageMockRecorder struct {
	mock *MockAbstrStorage
}

// NewMockAbstrStorage creates a new mock instance.
func NewMockAbstrStorage(ctrl *gomock.Controller) *MockAbstrStorage {
	mock := &MockAbstrStorage{ctrl: ctrl}
	mock.recorder = &MockAbstrStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAbstrStorage) EXPECT() *MockAbstrStorageMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockAbstrStorage) CreateOrder(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockAbstrStorageMockRecorder) CreateOrder(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockAbstrStorage)(nil).CreateOrder), arg0, arg1, arg2)
}

// SelectOrderByNumber mocks base method.
func (m *MockAbstrStorage) SelectOrderByNumber(arg0 context.Context, arg1 string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectOrderByNumber", arg0, arg1)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectOrderByNumber indicates an expected call of SelectOrderByNumber.
func (mr *MockAbstrStorageMockRecorder) SelectOrderByNumber(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectOrderByNumber", reflect.TypeOf((*MockAbstrStorage)(nil).SelectOrderByNumber), arg0, arg1)
}
