// Code generated by MockGen. DO NOT EDIT.
// Source: mishin-gophermat/internal/handlers/postwithdrawns (interfaces: WithdrawnCreator)

// Package postwithdrawns is a generated GoMock package.
package postwithdrawns

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWithdrawnCreator is a mock of WithdrawnCreator interface.
type MockWithdrawnCreator struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawnCreatorMockRecorder
}

// MockWithdrawnCreatorMockRecorder is the mock recorder for MockWithdrawnCreator.
type MockWithdrawnCreatorMockRecorder struct {
	mock *MockWithdrawnCreator
}

// NewMockWithdrawnCreator creates a new mock instance.
func NewMockWithdrawnCreator(ctrl *gomock.Controller) *MockWithdrawnCreator {
	mock := &MockWithdrawnCreator{ctrl: ctrl}
	mock.recorder = &MockWithdrawnCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawnCreator) EXPECT() *MockWithdrawnCreatorMockRecorder {
	return m.recorder
}

// BalanceGet mocks base method.
func (m *MockWithdrawnCreator) BalanceGet(arg0 context.Context, arg1 string) (float64, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BalanceGet", arg0, arg1)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BalanceGet indicates an expected call of BalanceGet.
func (mr *MockWithdrawnCreatorMockRecorder) BalanceGet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BalanceGet", reflect.TypeOf((*MockWithdrawnCreator)(nil).BalanceGet), arg0, arg1)
}

// WithdrawnCreate mocks base method.
func (m *MockWithdrawnCreator) WithdrawnCreate(arg0 context.Context, arg1, arg2 string, arg3 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawnCreate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawnCreate indicates an expected call of WithdrawnCreate.
func (mr *MockWithdrawnCreatorMockRecorder) WithdrawnCreate(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawnCreate", reflect.TypeOf((*MockWithdrawnCreator)(nil).WithdrawnCreate), arg0, arg1, arg2, arg3)
}
