// Code generated by MockGen. DO NOT EDIT.
// Source: mishin-gophermat/internal/handlers/postwithdrawns (interfaces: AbstrStorage)

// Package postwithdrawns is a generated GoMock package.
package postwithdrawns

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAbstrStorage is a mock of AbstrStorage interface.
type MockAbstrStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAbstrStorageMockRecorder
}

// MockAbstrStorageMockRecorder is the mock recorder for MockAbstrStorage.
type MockAbstrStorageMockRecorder struct {
	mock *MockAbstrStorage
}

// NewMockAbstrStorage creates a new mock instance.
func NewMockAbstrStorage(ctrl *gomock.Controller) *MockAbstrStorage {
	mock := &MockAbstrStorage{ctrl: ctrl}
	mock.recorder = &MockAbstrStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAbstrStorage) EXPECT() *MockAbstrStorageMockRecorder {
	return m.recorder
}

// CreateWithdrawn mocks base method.
func (m *MockAbstrStorage) CreateWithdrawn(arg0 context.Context, arg1, arg2 string, arg3 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdrawn", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithdrawn indicates an expected call of CreateWithdrawn.
func (mr *MockAbstrStorageMockRecorder) CreateWithdrawn(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdrawn", reflect.TypeOf((*MockAbstrStorage)(nil).CreateWithdrawn), arg0, arg1, arg2, arg3)
}

// SelectBalanceByLogin mocks base method.
func (m *MockAbstrStorage) SelectBalanceByLogin(arg0 context.Context, arg1 string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBalanceByLogin", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SelectBalanceByLogin indicates an expected call of SelectBalanceByLogin.
func (mr *MockAbstrStorageMockRecorder) SelectBalanceByLogin(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBalanceByLogin", reflect.TypeOf((*MockAbstrStorage)(nil).SelectBalanceByLogin), arg0, arg1)
}
