// Code generated by MockGen. DO NOT EDIT.
// Source: mishin-gophermat/internal/handlers/login (interfaces: AbstrStorage)

// Package login is a generated GoMock package.
package login

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAbstrStorage is a mock of AbstrStorage interface.
type MockAbstrStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAbstrStorageMockRecorder
}

// MockAbstrStorageMockRecorder is the mock recorder for MockAbstrStorage.
type MockAbstrStorageMockRecorder struct {
	mock *MockAbstrStorage
}

// NewMockAbstrStorage creates a new mock instance.
func NewMockAbstrStorage(ctrl *gomock.Controller) *MockAbstrStorage {
	mock := &MockAbstrStorage{ctrl: ctrl}
	mock.recorder = &MockAbstrStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAbstrStorage) EXPECT() *MockAbstrStorageMockRecorder {
	return m.recorder
}

// SelectUser mocks base method.
func (m *MockAbstrStorage) SelectUser(arg0 context.Context, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUser indicates an expected call of SelectUser.
func (mr *MockAbstrStorageMockRecorder) SelectUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUser", reflect.TypeOf((*MockAbstrStorage)(nil).SelectUser), arg0, arg1, arg2)
}
